You'll find 2 .csv files attached. Import both into your Jupyter notebook. 

The longley.csv file includes the follow data per year:

GNP deflator:percent of a dollar worth compared to 1954 (measure of inflation)

GNP: Gross national product in millions

Armed.Forces: number of people in the armed forces in hundreds of thousands

Population: population in millions

Unemployed is measured in thousands

Employed is measured in millions

How many rows and columns does the longley dataset contain? Enter as a tuple with a space after the comma: (r, c).

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
ld = pd.read_csv('longley.csv')
ld.head()
ld.shape

(16, 7)

In [9]:
ap = pd.read_csv('AirPass.csv')
ap.head()
ap.shape

(12, 13)

In [10]:
ld.head()

   Year  GNP.deflator      GNP  Unemployed  Armed.Forces  Population  Employed
0  1947          83.0  234.289       235.6         159.0     107.608    60.323
1  1948          88.5  259.426       232.5         145.6     108.632    61.122
2  1949          88.2  258.054       368.2         161.6     109.773    60.171
3  1950          89.5  284.599       335.1         165.0     110.929    61.187
4  1951          96.2  328.975       209.9         309.9     112.075    63.221

In [11]:
ap.head()

     yr  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
0  1949  112  118  132  129  121  135  148  148  136  119  104  118
1  1950  115  126  141  135  125  149  170  170  158  133  114  140
2  1951  145  150  178  163  172  178  199  199  184  162  146  166
3  1952  171  180  193  181  183  218  230  242  209  191  172  194
4  1953  196  196  236  235  229  243  264  272  237  211  180  201

Complete an inner join on the 2 datasets. How many rows and columns does the resulting dataset contain? Enter as a tuple.

In [16]:
merged = ld.merge(ap, left_on='Year', right_on='yr')
merged.head()

,Year,GNP.deflator,GNP,Unemployed,Armed.Forces,Population,Employed,yr,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1949,88.2,258.054,368.2,161.6,109.773,60.171,1949,112,118,132,129,121,135,148,148,136,119,104,118
1,1950,89.5,284.599,335.1,165.0,110.929,61.187,1950,115,126,141,135,125,149,170,170,158,133,114,140
2,1951,96.2,328.975,209.9,309.9,112.075,63.221,1951,145,150,178,163,172,178,199,199,184,162,146,166
3,1952,98.1,346.999,193.2,359.4,113.270,63.639,1952,171,180,193,181,183,218,230,242,209,191,172,194
4,1953,99.0,365.385,187.0,354.7,115.094,64.989,1953,196,196,236,235,229,243,264,272,237,211,180,201

In [17]:
merged.shape

(12, 20)

Complete an outer join on the 2 datasets. How many rows and columns does the resulting dataset contain? Enter as a tuple.

In [20]:
merged_outer = ld.merge(ap, left_on='Year', right_on='yr', how='outer')
merged_outer.head()

,Year,GNP.deflator,GNP,Unemployed,Armed.Forces,Population,Employed,yr,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1947,83.0,234.289,235.6,159.0,107.608,60.323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1948,88.5,259.426,232.5,145.6,108.632,61.122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1949,88.2,258.054,368.2,161.6,109.773,60.171,1949.0,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
3,1950,89.5,284.599,335.1,165.0,110.929,61.187,1950.0,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
4,1951,96.2,328.975,209.9,309.9,112.075,63.221,1951.0,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0

In [21]:
merged_outer.shape

(16, 20)